# Generated by Django 2.2.6 on 2019-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerGroupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNum', models.IntegerField()),
                ('roomNum', models.IntegerField()),
                ('project_name', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('advisor_name', models.CharField(max_length=20)),
                ('technical_accuracy', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('supporting_work', models.IntegerField()),
                ('design_process', models.IntegerField()),
                ('project_complexity', models.IntegerField()),
                ('completion', models.IntegerField()),
                ('tests', models.IntegerField()),
                ('response', models.IntegerField()),
                ('organization', models.IntegerField()),
                ('time', models.IntegerField()),
                ('visual', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('overview', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerSessionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('q11', models.IntegerField()),
                ('q12', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
