# Generated by Django 2.2.6 on 2019-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_auto_20191116_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='judgePermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_judge', 'This user is a judge')],
            },
        ),
    ]
