# Generated by Django 2.2.6 on 2019-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSessionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionNum', models.CharField(max_length=10)),
                ('roomNum', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('advisor_name', models.CharField(max_length=20)),
            ],
        ),
    ]
