# Generated by Django 2.2.7 on 2019-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191117_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='advisor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
