# Generated by Django 2.2.6 on 2019-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191117_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('is_admin', 'This user is an admin')],
            },
        ),
    ]
